const ROGProducts = {
    laptops: [
        {
            id: "rog-strix-scar-18-2025",
            name: "ROG Strix SCAR 18 (2025)",
            nameAz: "ROG Strix SCAR 18 (2025)",
            nameTr: "ROG Strix SCAR 18 (2025)",
            nameRu: "ROG Strix SCAR 18 (2025)",
            price: 3599.99,
            priceAz: 6119.99,
            priceTr: 119999.99,
            priceRu: 359999.99,
            category: "laptops",
            image: "rog-strix-scar-18.jpg",
            specs: "Intel Core Ultra 9 275HX, RTX 5090 24GB, 32GB DDR5-5600, 2TB PCIe 5.0 SSD, 18\" WQXGA 240Hz Mini-LED",
            specsAz: "Intel Core Ultra 9 275HX, RTX 5090 24GB, 32GB DDR5-5600, 2TB PCIe 5.0 SSD, 18\" WQXGA 240Hz Mini-LED",
            specsTr: "Intel Core Ultra 9 275HX, RTX 5090 24GB, 32GB DDR5-5600, 2TB PCIe 5.0 SSD, 18\" WQXGA 240Hz Mini-LED",
            specsRu: "Intel Core Ultra 9 275HX, RTX 5090 24GB, 32GB DDR5-5600, 2TB PCIe 5.0 SSD, 18\" WQXGA 240Hz Mini-LED",
            stock: 15,
            features: ["RGB Backlit Keyboard", "Liquid Metal Cooling", "Thunderbolt 5", "WiFi 7", "G-Sync"],
            featuresAz: ["RGB Arxa İşıqlı Klaviatura", "Maye Metal Soyutma", "Thunderbolt 5", "WiFi 7", "G-Sync"],
            featuresTr: ["RGB Arka Aydınlatmalı Klavye", "Sıvı Metal Soğutma", "Thunderbolt 5", "WiFi 7", "G-Sync"],
            featuresRu: ["RGB Подсветка Клавиатуры", "Жидкостное Охлаждение", "Thunderbolt 5", "WiFi 7", "G-Sync"]
        },
        {
            id: "rog-zephyrus-g14-2025",
            name: "ROG Zephyrus G14 (2025)",
            nameAz: "ROG Zephyrus G14 (2025)",
            nameTr: "ROG Zephyrus G14 (2025)",
            nameRu: "ROG Zephyrus G14 (2025)",
            price: 2399.99,
            priceAz: 4079.99,
            priceTr: 79999.99,
            priceRu: 239999.99,
            category: "laptops",
            image: "rog-zephyrus-g14.jpg",
            specs: "AMD Ryzen AI 9 HX 370, RTX 5080 16GB, 64GB LPDDR5X-7500, 2TB PCIe 5.0 SSD, 14\" 2.8K 165Hz OLED",
            specsAz: "AMD Ryzen AI 9 HX 370, RTX 5080 16GB, 64GB LPDDR5X-7500, 2TB PCIe 5.0 SSD, 14\" 2.8K 165Hz OLED",
            specsTr: "AMD Ryzen AI 9 HX 370, RTX 5080 16GB, 64GB LPDDR5X-7500, 2TB PCIe 5.0 SSD, 14\" 2.8K 165Hz OLED",
            specsRu: "AMD Ryzen AI 9 HX 370, RTX 5080 16GB, 64GB LPDDR5X-7500, 2TB PCIe 5.0 SSD, 14\" 2.8K 165Hz OLED",
            stock: 23,
            features: ["AniMe Matrix Display", "Ultra Portable", "All-Day Battery", "WiFi 7", "USB4"],
            featuresAz: ["AniMe Matrix Ekranı", "Ultra Daşınabilir", "Gün Boyu Baterya", "WiFi 7", "USB4"],
            featuresTr: ["AniMe Matrix Ekran", "Ultra Taşınabilir", "Tüm Gün Batarya", "WiFi 7", "USB4"],
            featuresRu: ["AniMe Matrix Дисплей", "Ультра Портативный", "Целый День Батарея", "WiFi 7", "USB4"]
        },
        {
            id: "rog-strix-g16-2025",
            name: "ROG Strix G16 (2025)",
            nameAz: "ROG Strix G16 (2025)",
            nameTr: "ROG Strix G16 (2025)",
            nameRu: "ROG Strix G16 (2025)",
            price: 1499.99,
            priceAz: 2549.99,
            priceTr: 49999.99,
            priceRu: 149999.99,
            category: "laptops",
            image: "rog-strix-g16.jpg",
            specs: "Intel Core i7-14650HX, RTX 5060 8GB, 16GB DDR5-4800, 1TB PCIe 4.0 SSD, 16\" FHD+ 165Hz",
            specsAz: "Intel Core i7-14650HX, RTX 5060 8GB, 16GB DDR5-4800, 1TB PCIe 4.0 SSD, 16\" FHD+ 165Hz",
            specsTr: "Intel Core i7-14650HX, RTX 5060 8GB, 16GB DDR5-4800, 1TB PCIe 4.0 SSD, 16\" FHD+ 165Hz",
            specsRu: "Intel Core i7-14650HX, RTX 5060 8GB, 16GB DDR5-4800, 1TB PCIe 4.0 SSD, 16\" FHD+ 165Hz",
            stock: 31,
            features: ["MUX Switch", "RGB Keyboard", "Advanced Cooling", "Thunderbolt 4", "WiFi 6E"],
            featuresAz: ["MUX Açarı", "RGB Klaviatura", "Qabaqcıl Soyutma", "Thunderbolt 4", "WiFi 6E"],
            featuresTr: ["MUX Anahtarı", "RGB Klavye", "Gelişmiş Soğutma", "Thunderbolt 4", "WiFi 6E"],
            featuresRu: ["MUX Переключатель", "RGB Клавиатура", "Продвинутое Охлаждение", "Thunderbolt 4", "WiFi 6E"]
        }
    ],
    phones: [
        {
            id: "rog-phone-9",
            name: "ROG Phone 9",
            nameAz: "ROG Phone 9",
            nameTr: "ROG Phone 9",
            nameRu: "ROG Phone 9",
            price: 899.99,
            priceAz: 1529.99,
            priceTr: 29999.99,
            priceRu: 89999.99,
            category: "phones",
            image: "rog-phone-9.jpg",
            specs: "Snapdragon 8 Elite, 16GB RAM, 512GB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Fast Charge",
            specsAz: "Snapdragon 8 Elite, 16GB RAM, 512GB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Sürətli Şarj",
            specsTr: "Snapdragon 8 Elite, 16GB RAM, 512GB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Hızlı Şarj",
            specsRu: "Snapdragon 8 Elite, 16GB RAM, 512GB UFS 4.0, 6.78\" AMOLED 185Hz, 5800мАч, 65W Быстрая Зарядка",
            stock: 42,
            features: ["RGB Logo", "AirTrigger 7", "GameCool 9", "Stereo Speakers", "3.5mm Jack"],
            featuresAz: ["RGB Logo", "AirTrigger 7", "GameCool 9", "Stereo Dinamiklər", "3.5mm Jack"],
            featuresTr: ["RGB Logo", "AirTrigger 7", "GameCool 9", "Stereo Hoparlörler", "3.5mm Jack"],
            featuresRu: ["RGB Логотип", "AirTrigger 7", "GameCool 9", "Стерео Динамики", "3.5mm Разъем"]
        },
        {
            id: "rog-phone-9-pro",
            name: "ROG Phone 9 Pro",
            nameAz: "ROG Phone 9 Pro",
            nameTr: "ROG Phone 9 Pro",
            nameRu: "ROG Phone 9 Pro",
            price: 1199.99,
            priceAz: 2039.99,
            priceTr: 39999.99,
            priceRu: 119999.99,
            category: "phones",
            image: "rog-phone-9-pro.jpg",
            specs: "Snapdragon 8 Elite, 24GB RAM, 1TB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Fast Charge",
            specsAz: "Snapdragon 8 Elite, 24GB RAM, 1TB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Sürətli Şarj",
            specsTr: "Snapdragon 8 Elite, 24GB RAM, 1TB UFS 4.0, 6.78\" AMOLED 185Hz, 5800mAh, 65W Hızlı Şarj",
            specsRu: "Snapdragon 8 Elite, 24GB RAM, 1TB UFS 4.0, 6.78\" AMOLED 185Hz, 5800мАч, 65W Быстрая Зарядка",
            stock: 18,
            features: ["AniMe Vision", "AirTrigger 7", "GameCool 9", "Wireless Charging", "Premium Audio"],
            featuresAz: ["AniMe Vision", "AirTrigger 7", "GameCool 9", "Simless Şarj", "Premium Audio"],
            featuresTr: ["AniMe Vision", "AirTrigger 7", "GameCool 9", "Kablosuz Şarj", "Premium Audio"],
            featuresRu: ["AniMe Vision", "AirTrigger 7", "GameCool 9", "Беспроводная Зарядка", "Премиум Аудио"]
        }
    ],
    desktops: [
        {
            id: "rog-g700-2025",
            name: "ROG G700 Gaming Desktop (2025)",
            nameAz: "ROG G700 Oyun Kompüteri (2025)",
            nameTr: "ROG G700 Oyun Masaüstü (2025)",
            nameRu: "ROG G700 Игровой Десктоп (2025)",
            price: 2999.99,
            priceAz: 5099.99,
            priceTr: 99999.99,
            priceRu: 299999.99,
            category: "desktops",
            image: "rog-g700.jpg",
            specs: "Intel Core i9-14900K, RTX 5080 16GB, 64GB DDR5-6000, 4TB PCIe 5.0 SSD, 1000W PSU, Custom Liquid Cooling",
            specsAz: "Intel Core i9-14900K, RTX 5080 16GB, 64GB DDR5-6000, 4TB PCIe 5.0 SSD, 1000W PSU, Xüsusi Maye Soyutma",
            specsTr: "Intel Core i9-14900K, RTX 5080 16GB, 64GB DDR5-6000, 4TB PCIe 5.0 SSD, 1000W PSU, Özel Sıvı Soğutma",
            specsRu: "Intel Core i9-14900K, RTX 5080 16GB, 64GB DDR5-6000, 4TB PCIe 5.0 SSD, 1000W БП, Собственное Охлаждение",
            stock: 8,
            features: ["RGB Lighting", "Tempered Glass", "Tool-less Design", "Premium Audio", "Advanced Cooling"],
            featuresAz: ["RGB İşıqlandırma", "Süfrəli Şüşə", "Alətsiz Dizayn", "Premium Audio", "Qabaqcıl Soyutma"],
            featuresTr: ["RGB Aydınlatma", "Camlı Panel", "Aletsiz Tasarım", "Premium Audio", "Gelişmiş Soğutma"],
            featuresRu: ["RGB Подсветка", "Закаленное Стекло", "Безинструментальный Дизайн", "Премиум Аудио", "Продвинутое Охлаждение"]
        }
    ],
    motherboards: [
        {
            id: "rog-crosshair-x870e-extreme",
            name: "ROG Crosshair X870E Extreme",
            nameAz: "ROG Crosshair X870E Extreme",
            nameTr: "ROG Crosshair X870E Extreme",
            nameRu: "ROG Crosshair X870E Extreme",
            price: 899.99,
            priceAz: 1529.99,
            priceTr: 29999.99,
            priceRu: 89999.99,
            category: "motherboards",
            image: "rog-crosshair-x870e.jpg",
            specs: "AMD AM5 Socket, X870E Chipset, 4x DDR5 Slots, 2x PCIe 5.0 x16, 5x M.2 Slots, WiFi 7, 5Gb Ethernet",
            specsAz: "AMD AM5 Soket, X870E Çipset, 4x DDR5 Slot, 2x PCIe 5.0 x16, 5x M.2 Slot, WiFi 7, 5Gb Ethernet",
            specsTr: "AMD AM5 Soket, X870E Çipset, 4x DDR5 Slot, 2x PCIe 5.0 x16, 5x M.2 Slot, WiFi 7, 5Gb Ethernet",
            specsRu: "AMD AM5 Сокет, X870E Чипсет, 4x DDR5 Слот, 2x PCIe 5.0 x16, 5x M.2 Слот, WiFi 7, 5Gb Ethernet",
            stock: 12,
            features: ["Extreme OC Kit", "5\" LCD Panel", "Q-Design", "WiFi 7", "PCIe 5.0"],
            featuresAz: ["Extreme OC Kit", "5\" LCD Panel", "Q-Dizayn", "WiFi 7", "PCIe 5.0"],
            featuresTr: ["Extreme OC Kit", "5\" LCD Panel", "Q-Tasarım", "WiFi 7", "PCIe 5.0"],
            featuresRu: ["Extreme OC Kit", "5\" LCD Панель", "Q-Дизайн", "WiFi 7", "PCIe 5.0"]
        },
        {
            id: "rog-strix-x870e-h-gaming",
            name: "ROG Strix X870E-H Gaming WiFi7",
            nameAz: "ROG Strix X870E-H Gaming WiFi7",
            nameTr: "ROG Strix X870E-H Gaming WiFi7",
            nameRu: "ROG Strix X870E-H Gaming WiFi7",
            price: 449.99,
            priceAz: 764.99,
            priceTr: 14999.99,
            priceRu: 44999.99,
            category: "motherboards",
            image: "rog-strix-x870e-h.jpg",
            specs: "AMD AM5 Socket, X870E Chipset, 4x DDR5 Slots, PCIe 5.0 x16, 4x M.2 Slots, WiFi 7, 5Gb Ethernet",
            specsAz: "AMD AM5 Soket, X870E Çipset, 4x DDR5 Slot, PCIe 5.0 x16, 4x M.2 Slot, WiFi 7, 5Gb Ethernet",
            specsTr: "AMD AM5 Soket, X870E Çipset, 4x DDR5 Slot, PCIe 5.0 x16, 4x M.2 Slot, WiFi 7, 5Gb Ethernet",
            specsRu: "AMD AM5 Сокет, X870E Чипсет, 4x DDR5 Слот, PCIe 5.0 x16, 4x M.2 Слот, WiFi 7, 5Gb Ethernet",
            stock: 27,
            features: ["14x USB Ports", "USB4 Support", "30W PD", "Q-Features", "Aura Sync"],
            featuresAz: ["14x USB Port", "USB4 Dəstəyi", "30W PD", "Q-Xüsusiyyətlər", "Aura Sync"],
            featuresTr: ["14x USB Port", "USB4 Desteği", "30W PD", "Q-Özellikler", "Aura Sync"],
            featuresRu: ["14x USB Порт", "USB4 Поддержка", "30W PD", "Q-Функции", "Aura Sync"]
        }
    ],
    cases: [
        {
            id: "rog-strix-helios-ii",
            name: "ROG Strix Helios II",
            nameAz: "ROG Strix Helios II",
            nameTr: "ROG Strix Helios II",
            nameRu: "ROG Strix Helios II",
            price: 299.99,
            priceAz: 509.99,
            priceTr: 9999.99,
            priceRu: 29999.99,
            category: "cases",
            image: "rog-strix-helios-ii.jpg",
            specs: "Full Tower, Tempered Glass, RGB Lighting, USB-C Front Panel, E-ATX Support, Premium Cable Management",
            specsAz: "Full Tower, Süfrəli Şüşə, RGB İşıqlandırma, USB-C Ön Panel, E-ATX Dəstəyi, Premium Kabel İdarəetmə",
            specsTr: "Full Tower, Camlı Panel, RGB Aydınlatma, USB-C Ön Panel, E-ATX Desteği, Premium Kablo Yönetimi",
            specsRu: "Full Tower, Закаленное Стекло, RGB Подсветка, USB-C Фронтальная Панель, E-ATX Поддержка, Премиум Управление Кабелями",
            stock: 19,
            features: ["Tempered Glass", "RGB Sync", "USB-C Front", "Cable Management", "E-ATX Support"],
            featuresAz: ["Süfrəli Şüşə", "RGB Sinxron", "USB-C Ön", "Kabel İdarəetmə", "E-ATX Dəstəyi"],
            featuresTr: ["Camlı Panel", "RGB Senkron", "USB-C Ön", "Kablo Yönetimi", "E-ATX Desteği"],
            featuresRu: ["Закаленное Стекло", "RGB Синхронизация", "USB-C Фронт", "Управление Кабелями", "E-ATX Поддержка"]
        },
        {
            id: "asus-a23-miku-edition",
            name: "ASUS A23 Hatsune Miku Edition",
            nameAz: "ASUS A23 Hatsune Miku Edition",
            nameTr: "ASUS A23 Hatsune Miku Edition",
            nameRu: "ASUS A23 Hatsune Miku Edition",
            price: 199.99,
            priceAz: 339.99,
            priceTr: 6666.99,
            priceRu: 19999.99,
            category: "cases",
            image: "asus-a23-miku.jpg",
            specs: "Mid Tower, Teal/Pink Design, Tempered Glass, Micro-ATX/ATX Support, Special Edition",
            specsAz: "Mid Tower, Mavi/Çəhrayı Dizayn, Süfrəli Şüşə, Micro-ATX/ATX Dəstəyi, Xüsusi Edition",
            specsTr: "Mid Tower, Turkuaz/Pembe Tasarım, Camlı Panel, Micro-ATX/ATX Desteği, Özel Seri",
            specsRu: "Mid Tower, Бирюзовый/Розовый Дизайн, Закаленное Стекло, Micro-ATX/ATX Поддержка, Специальное Издание",
            stock: 25,
            features: ["Special Edition", "Unique Colors", "Tempered Glass", "Compact Design", "RGB Ready"],
            featuresAz: ["Xüsusi Edition", "Unikal Rənglər", "Süfrəli Şüşə", "Kompakt Dizayn", "RGB Hazır"],
            featuresTr: ["Özel Seri", "Benzersiz Renkler", "Camlı Panel", "Kompakt Tasarım", "RGB Hazır"],
            featuresRu: ["Специальное Издание", "Уникальные Цвета", "Закаленное Стекло", "Компактный Дизайн", "RGB Готов"]
        }
    ],
    graphics: [
        {
            id: "rog-astral-rtx-5090",
            name: "ROG Astral RTX 5090",
            nameAz: "ROG Astral RTX 5090",
            nameTr: "ROG Astral RTX 5090",
            nameRu: "ROG Astral RTX 5090",
            price: 1999.99,
            priceAz: 3399.99,
            priceTr: 66666.99,
            priceRu: 199999.99,
            category: "graphics",
            image: "rog-astral-rtx-5090.jpg",
            specs: "GeForce RTX 5090 32GB GDDR7, Quad-Fan Design, Vapor Chamber, Phase-Change Thermal Pad, PCIe 5.0",
            specsAz: "GeForce RTX 5090 32GB GDDR7, Dörd Fanlı Dizayn, Buxar Kamerası, Phase-Change Termal Pad, PCIe 5.0",
            specsTr: "GeForce RTX 5090 32GB GDDR7, Dört Fanlı Tasarım, Buhar Odası, Phase-Change Termal Pad, PCIe 5.0",
            specsRu: "GeForce RTX 5090 32GB GDDR7, Четырехвентиляторный Дизайн, Вакуумная Камера, Phase-Change Термопрокладка, PCIe 5.0",
            stock: 6,
            features: ["Quad-Fan", "Vapor Chamber", "32GB GDDR7", "PCIe 5.0", "Premium Build"],
            featuresAz: ["Dörd Fan", "Buxar Kamerası", "32GB GDDR7", "PCIe 5.0", "Premium Dizayn"],
            featuresTr: ["Dört Fan", "Buhar Odası", "32GB GDDR7", "PCIe 5.0", "Premium Tasarım"],
            featuresRu: ["Четыре Вентилятора", "Вакуумная Камера", "32GB GDDR7", "PCIe 5.0", "Премиум Дизайн"]
        },
        {
            id: "rog-astral-rtx-5080",
            name: "ROG Astral RTX 5080",
            nameAz: "ROG Astral RTX 5080",
            nameTr: "ROG Astral RTX 5080",
            nameRu: "ROG Astral RTX 5080",
            price: 1299.99,
            priceAz: 2209.99,
            priceTr: 43333.99,
            priceRu: 129999.99,
            category: "graphics",
            image: "rog-astral-rtx-5080.jpg",
            specs: "GeForce RTX 5080 16GB GDDR7, Quad-Fan Design, Vapor Chamber, Phase-Change Thermal Pad, PCIe 5.0",
            specsAz: "GeForce RTX 5080 16GB GDDR7, Dörd Fanlı Dizayn, Buxar Kamerası, Phase-Change Termal Pad, PCIe 5.0",
            specsTr: "GeForce RTX 5080 16GB GDDR7, Dört Fanlı Tasarım, Buhar Odası, Phase-Change Termal Pad, PCIe 5.0",
            specsRu: "GeForce RTX 5080 16GB GDDR7, Четырехвентиляторный Дизайн, Вакуумная Камера, Phase-Change Термопрокладка, PCIe 5.0",
            stock: 14,
            features: ["Quad-Fan", "Vapor Chamber", "16GB GDDR7", "PCIe 5.0", "Premium Build"],
            featuresAz: ["Dörd Fan", "Buxar Kamerası", "16GB GDDR7", "PCIe 5.0", "Premium Dizayn"],
            featuresTr: ["Dört Fan", "Buhar Odası", "16GB GDDR7", "PCIe 5.0", "Premium Tasarım"],
            featuresRu: ["Четыре Вентилятора", "Вакуумная Камера", "16GB GDDR7", "PCIe 5.0", "Премиум Дизайн"]
        }
    ],
    accessories: [
        {
            id: "rog-ryuo-iv-360",
            name: "ROG Ryuo IV 360 ARGB",
            nameAz: "ROG Ryuo IV 360 ARGB",
            nameTr: "ROG Ryuo IV 360 ARGB",
            nameRu: "ROG Ryuo IV 360 ARGB",
            price: 399.99,
            priceAz: 679.99,
            priceTr: 13333.99,
            priceRu: 39999.99,
            category: "accessories",
            image: "rog-ryuo-iv-360.jpg",
            specs: "360mm AIO Cooler, 6.67\" AMOLED Display, RGB Fans, Intel/AMD Compatible, Premium Tubing",
            specsAz: "360mm AIO Soyutma, 6.67\" AMOLED Ekran, RGB Fanlar, Intel/AMD Uyumlu, Premium Borular",
            specsTr: "360mm AIO Soğutma, 6.67\" AMOLED Ekran, RGB Fanlar, Intel/AMD Uyumlu, Premium Tüpler",
            specsRu: "360mm AIO Охлаждение, 6.67\" AMOLED Дисплей, RGB Вентиляторы, Intel/AMD Совместимость, Премиум Трубки",
            stock: 34,
            features: ["6.67\" Display", "RGB Lighting", "360mm Radiator", "Premium Build", "Wide Compatibility"],
            featuresAz: ["6.67\" Ekran", "RGB İşıqlandırma", "360mm Radiator", "Premium Dizayn", "Geniş Uyumluluq"],
            featuresTr: ["6.67\" Ekran", "RGB Aydınlatma", "360mm Radyatör", "Premium Tasarım", "Geniş Uyumluluk"],
            featuresRu: ["6.67\" Дисплей", "RGB Подсветка", "360mm Радиатор", "Премиум Дизайн", "Широкая Совместимость"]
        },
        {
            id: "rog-thor-1200w",
            name: "ROG Thor 1200W Platinum III",
            nameAz: "ROG Thor 1200W Platinum III",
            nameTr: "ROG Thor 1200W Platinum III",
            nameRu: "ROG Thor 1200W Platinum III",
            price: 449.99,
            priceAz: 764.99,
            priceTr: 14999.99,
            priceRu: 44999.99,
            category: "accessories",
            image: "rog-thor-1200w.jpg",
            specs: "1200W Power Supply, 80+ Platinum, OLED Display, ROG Thermal Solution, Modular Cables",
            specsAz: "1200W Enerji Mənbəsi, 80+ Platinum, OLED Ekran, ROG Termal Həlli, Modulyar Kabellər",
            specsTr: "1200W Güç Kaynağı, 80+ Platinum, OLED Ekran, ROG Termal Çözümü, Modüler Kablolar",
            specsRu: "1200W Блок Питания, 80+ Platinum, OLED Дисплей, ROG Термальное Решение, Модульные Кабели",
            stock: 21,
            features: ["1200W Power", "Platinum Rating", "OLED Display", "Modular Cables", "Premium Cooling"],
            featuresAz: ["1200W Güc", "Platinum Reytinq", "OLED Ekran", "Modulyar Kabellər", "Premium Soyutma"],
            featuresTr: ["1200W Güç", "Platinum Derece", "OLED Ekran", "Modüler Kablolar", "Premium Soğutma"],
            featuresRu: ["1200W Мощность", "Platinum Рейтинг", "OLED Дисплей", "Модульные Кабели", "Премиум Охлаждение"]
        }
    ]
};

const siteConfig = {
    currencies: {
        USD: { symbol: '$', name: 'US Dollar', rate: 1 },
        AZN: { symbol: '₼', name: 'Azerbaijani Manat', rate: 1.7 },
        TRY: { symbol: '₺', name: 'Turkish Lira', rate: 33.33 },
        RUB: { symbol: '₽', name: 'Russian Ruble', rate: 100 }
    },
    languages: {
        en: { name: 'English', flag: '🇺🇸' },
        az: { name: 'Azerbaijani', flag: '🇦🇿' },
        tr: { name: 'Turkish', flag: '🇹🇷' },
        ru: { name: 'Russian', flag: '🇷🇺' }
    }
};